# -*- coding: utf-8 -*-
"""Dimension reduction of corpus truncated SVD

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Cuk65_IaFK9MM5_ZPv1E4aanJ3oh8zo
"""

from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np # linear algebra
import matplotlib
import pandas as pd

from sklearn.decomposition import TruncatedSVD

# Load the data and create document vectors
corpus = pd.read_csv('../content/data_poynter_2020-04-24.csv') #location of .csv file
tfidf = TfidfVectorizer() 
X = tfidf.fit_transform(corpus)

corpus.head()

y = corpus.label

svd = TruncatedSVD(n_components=5, n_iter=7, random_state=42)
 X_svd = svd.fit(X)

print(svd.explained_variance_ratio_)

print(svd.explained_variance_ratio_.sum())

print(svd.singular_values_)