"""empty message

Revision ID: a2992d4a8756
Revises: 
Create Date: 2020-06-01 22:14:37.286054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2992d4a8756'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('check_claim', sa.String(), nullable=False),
    sa.Column('feedback_label', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['original_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('basic__user')
    op.add_column('claims', sa.Column('feedback_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('labels', sa.Column('label', sa.Integer(), nullable=False))
    op.drop_column('labels', 'feedback_label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('feedback_label', sa.INTEGER(), nullable=False))
    op.drop_column('labels', 'label')
    op.drop_column('claims', 'feedback_count')
    op.create_table('basic__user',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.INTEGER(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('feedback')
    # ### end Alembic commands ###
